### ISSUE TITLE
ZC158: admin, products price manager orphan text "Linked Product 146" with php8

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4615]
Enter into page:
![ppm](https://user-images.githubusercontent.com/4391026/153927519-121b0a07-3084-4f90-a498-ab6dbc2fe4fd.gif)

**Comment by scottcwilson** [comment]
I think you have diddled your database; this doesn't happen to me.

**Comment by torvista** [comment]
It occurs in php8, not earlier. Same sort of comparison issue that is resolved in my pending PR for attributes controller:
https://github.com/zencart/zencart/pull/4501

Here, $product_filter is 0 and so zen_get_product_is_linked returns true and the orphan text is outputted.
https://github.com/zencart/zencart/blob/ceb20b8b2bad321a21427d2cc3b40e23ababab99/admin/products_price_manager.php#L296-L300

**Comment by proseLA** [comment]
confirmed bug under php 8.1:

![image](https://user-images.githubusercontent.com/1095136/153974052-8f90ee68-7274-4838-b680-c39f403079b5.png)

i also can confirm #4501 does NOT resolve this issue.

this specific one happens here:

https://github.com/zencart/zencart/blob/ceb20b8b2bad321a21427d2cc3b40e23ababab99/admin/products_price_manager.php#L297

under php8.1 the correct conditional should `$products_filter !== 0`.

it seems there are a couple of other places in the same script that would need addressing.

**Comment by scottcwilson** [comment]
Thanks for this extra detail.  Please PR.

**Comment by scottcwilson** [comment]
@proseLA @torvista Would you please submit a PR for this? Would like to get it into 158.  Thanks.

**Comment by torvista** [comment]
At the moment I have no time for anything other than short comments about a lack of time.
